modLoader = "javafml"
loaderVersion = "[1,)"
license = "All Rights Reserved"

[[mods]]
modId = "chestseparators"
version = "${version}"
displayName = "Absolute Order"
authors = "marcsanz-dev"
logoFile = "icon.png"
description = '''
Custom chest auto-sorter with visual separators and per-slot filters.
'''

[[dependencies.chestseparators]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chestseparators]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chestseparators]]
modId = "cloth_config"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.chestseparators]]
modId = "architectury"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "absoluteorder.mixins.json"

[[mixins]]
config = 'absoluteorder.neoforge.mixins.json'
